DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
                          NOMBRE VARCHAR(100),
                          APELLIDO VARCHAR(100));

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES
    (789651 ,'Juan','Perez');

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES
    (845624 ,'Pedro','Villane');

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES
    (765423 ,'Marcos','Rodriguez');

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES
    (693541 ,'Emanuel','Sanchez');